"use client"
import Navbar from '@/components/Navbar'
import './globals.css'
import { Roboto_Mono } from 'next/font/google'
import { ThemeProvider } from 'next-themes'
import Footer from '@/components/Footer'

const inter = Roboto_Mono({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider enableSystem={true} attribute='class'>
        <Navbar />
        {children}
        <Footer />
        </ThemeProvider>
        </body>
    </html>
  )
}
